# Generated by Django 6.0.6 on 2026-06-27 12:31

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge/')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_ingested', models.BooleanField(default=False, verbose_name='Ingerido')),
                ('fault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='faults.fault', verbose_name='Defeito associado')),
            ],
            options={
                'verbose_name': 'Documento Orientativo',
                'verbose_name_plural': 'Documentos Orientativos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('chunk_index', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Chunk de Documento',
                'verbose_name_plural': 'Chunks de Documento',
                'ordering': ['document', 'chunk_index'],
            },
        ),
    ]
