# Generated by Django 6.0.6 on 2026-06-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_readings', models.IntegerField(default=0)),
                ('problem_readings', models.IntegerField(default=0)),
                ('state_readings', models.IntegerField(default=0)),
                ('pending_readings', models.IntegerField(default=0)),
                ('total_prescriptions', models.IntegerField(default=0)),
                ('grounded_prescriptions', models.IntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Snapshot do Dashboard',
                'ordering': ['-created_at'],
            },
        ),
    ]
