# Generated by Django 6.0.6 on 2026-06-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Ex: cocked_rotor_2, normal, unbalance', max_length=100, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('is_problem', models.BooleanField(default=True, help_text='False = estado operacional normal', verbose_name='É problema?')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Defeito/Estado',
                'verbose_name_plural': 'Defeitos/Estados',
                'ordering': ['-is_problem', 'code'],
            },
        ),
    ]
