# Generated by Django 6.0.6 on 2026-06-27 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('equipment_type', models.CharField(help_text='Ex: motor, bomba, compressor', max_length=100, verbose_name='Tipo')),
                ('sector', models.CharField(max_length=200, verbose_name='Setor/Planta')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('maintenance', 'Em Manutenção')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('axis', models.CharField(choices=[('X', 'X'), ('Z', 'Z'), ('XZ', 'X e Z')], default='XZ', max_length=5, verbose_name='Eixo')),
                ('sensor_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de sensor')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_points', to='assets.equipment')),
            ],
            options={
                'verbose_name': 'Ponto de Medição',
                'verbose_name_plural': 'Pontos de Medição',
                'ordering': ['equipment', 'name'],
            },
        ),
    ]
