# Generated by Django 6.0.6 on 2026-06-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faults', '0001_initial'),
        ('knowledge', '0001_initial'),
        ('monitoring', '0002_sensorreading_vector_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defect_type', models.CharField(blank=True, max_length=200, verbose_name='Tipo de defeito')),
                ('occurrences_count', models.IntegerField(default=0, verbose_name='Qtd. ocorrências')),
                ('occurrences_frequency', models.CharField(blank=True, max_length=300, verbose_name='Frequência')),
                ('instructions', models.TextField(blank=True, verbose_name='Instruções (Markdown)')),
                ('is_grounded', models.BooleanField(default=True, help_text='False = acionou regra de guarda (sem documentação)', verbose_name='Fundamentada')),
                ('pipeline_log', models.JSONField(blank=True, default=dict, verbose_name='Log do pipeline')),
                ('fault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='faults.fault')),
                ('sensor_reading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='monitoring.sensorreading')),
                ('source_chunks', models.ManyToManyField(blank=True, related_name='prescriptions', to='knowledge.documentchunk')),
            ],
            options={
                'verbose_name': 'Prescrição',
                'verbose_name_plural': 'Prescrições',
                'ordering': ['-created_at'],
            },
        ),
    ]
