# Generated by Django 6.0.6 on 2026-06-27 05:22

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('faults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.BigIntegerField(blank=True, db_index=True, help_text='ID de origem para idempotência', null=True, unique=True, verbose_name='ID externo')),
                ('metrics', models.JSONField(help_text='Todas as colunas do evento original', verbose_name='Métricas brutas')),
                ('feature_vector', pgvector.django.vector.VectorField(blank=True, dimensions=18, null=True)),
                ('status_class', models.CharField(choices=[('pending', 'Aguardando análise'), ('state', 'Estado operacional'), ('problem', 'Problema detectado')], default='pending', max_length=10)),
                ('rpm', models.FloatField(blank=True, null=True)),
                ('event_created_at', models.DateTimeField(blank=True, null=True)),
                ('fault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='faults.fault')),
                ('measurement_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='assets.measurementpoint')),
            ],
            options={
                'verbose_name': 'Leitura de Sensor',
                'verbose_name_plural': 'Leituras de Sensor',
                'ordering': ['-event_created_at'],
            },
        ),
    ]
