# Generated by Django 6.0.6 on 2026-06-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('inbound', 'Recebida'), ('outbound', 'Enviada')], max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('message_id', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
